name: ".NET Framework Desktop"

on:
  push:
    branches: [ main ]
env:
  solution: 'SampleApplication/SampleApplication.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  DEV:
    runs-on: windows-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1    
    - run: nuget restore '${{ env.solution }}'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - run: msbuild '${{ env.solution }}' /p:Configuration='${{ env.buildConfiguration }}' /p:platform='${{ env.buildPlatform }}'
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
            name: App.config
            path: ./App.config

    

  copy-file:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'test_files'
        destination_repo: 'dmnemec/Tilt'
        destination_folder: 'Tilt'
        user_email: 'subaveethividangan@gmail.com'
        user_name: 'Abinash-8892'
        commit_msg: '[GHA] Update the test files.'
    
  QA:
    runs-on: windows-latest
    environment: QA
    needs: DEV
    

    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1    
    - run: nuget restore '${{ env.solution }}'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - run: msbuild '${{ env.solution }}' /p:Configuration='${{ env.buildConfiguration }}' /p:platform='${{ env.buildPlatform }}'
    
  PROD:
    runs-on: windows-latest
    environment: PROD
    needs: QA

    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1    
    - run: nuget restore '${{ env.solution }}'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - run: msbuild '${{ env.solution }}' /p:Configuration='${{ env.buildConfiguration }}' /p:platform='${{ env.buildPlatform }}'
